---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fung-{{ .Release.Name }}
      tier: backend
  template:
    metadata:
      labels:
        app: fung-{{ .Release.Name }}
        tier: backend
    spec:
      containers:
        - name: echo-{{ .Release.Name }}
          image: "ealen/echo-server:latest"
          ports:
            - containerPort: 8000
          env: 
            - name: PORT
              value: 8000 
        
