apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-ingress-{{ .Release.Name }}
spec:
  rules:
    - host: "{{ .Values.application.ingress.host }}"
      http:
        paths:
          - path: "{{ .Values.application.ingress.path }}"
            backend:
              serviceName: frontend-{{ .Release.Name }}
              servicePort: {{ .Values.frontend.port }}
    - host: "{{ .Values.application.ingress.host }}"
      http:
        paths:
          - pathType: Prefix
            path: "/{{ .Values.application.ingress.socket_prefix }}/"
            backend:
              serviceName: backend-{{ .Release.Name }}
              servicePort: {{ .Values.backend.port }}
  tls:
    - hosts:
        - "{{ .Values.application.ingress.host }}"
      secretName: "{{ .Values.application.ingress.secretName }}"