apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: redis-{{ .Release.Name }}
    spec:
      containers:
        - name: redis-{{ .Release.Name }}
          image: "{{ .Values.redis.image }}:{{ .Values.redis.tag }}"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-{{ .Release.Name }}
spec:
  selector:
    app: redis-{{ .Release.Name }}
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: 6379 