# Generated by Django 4.0 on 2021-12-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guess',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
