# Generated by Django 4.0 on 2021-12-13 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_id_player_name_player_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='player',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='token',
        ),
        migrations.AddField(
            model_name='entry',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='name', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='price',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
