# Generated by Django 4.0 on 2021-12-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_guess_alter_entry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
