# Generated by Django 4.0 on 2021-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_entry_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rounds',
            field=models.IntegerField(default=10),
        ),
    ]
