name: CI / CD
on: push
jobs:
  frontend-build:
      name: Build and publish frontend
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
        
          - name: Cache Docker layers
            uses: actions/cache@v2
            with:
              path: /tmp/.buildx-cache
              key: ${{ runner.os }}-buildx-${{ github.sha }}
              restore-keys: |
                ${{ runner.os }}-buildx-

          - name: Login to GHCR
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: $GITHUB_ACTOR
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push image
            uses: docker/build-push-action@v2
            with:
              context: frontend
              push: ${{ github.ref == 'refs/heads/main' }}
              tags: "ghcr.io/sigmachirality/gofungyourself-frontend:${{ github.sha }},ghcr.io/sigmachirality/gofungyourself-frontend:latest"
              cache-from: type=local,src=/tmp/.buildx-cache
              cache-to: type=local,dest=/tmp/.buildx-cache-new

          - name: Move cache
            run: |
                rm -rf /tmp/.buildx-cache
                mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  backend-build:
      name: Build and publish backend
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
        
          - name: Cache Docker layers
            uses: actions/cache@v2
            with:
              path: /tmp/.buildx-cache
              key: ${{ runner.os }}-buildx-${{ github.sha }}
              restore-keys: |
                ${{ runner.os }}-buildx-

          - name: Login to GHCR
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: $GITHUB_ACTOR
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push image
            uses: docker/build-push-action@v2
            with:
              context: backend
              push: ${{ github.ref == 'refs/heads/main' }}
              tags: "ghcr.io/sigmachirality/gofungyourself-backend:${{ github.sha }},ghcr.io/sigmachirality/gofungyourself-backend:latest"
              cache-from: type=local,src=/tmp/.buildx-cache
              cache-to: type=local,dest=/tmp/.buildx-cache-new

          - name: Move cache
            run: |
                rm -rf /tmp/.buildx-cache
                mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  deploy:
    name: Deploy to test environment
    if: github.ref == 'refs/heads/main'
    needs: [frontend-build, backend-build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name cis188 --role-arn arn:aws:iam::474844133309:role/simono --alias fung
          kubectl config set-context --current --namespace=simono
      - name: Apply helm charts
        run: |
          helm upgrade --install test deploy \
          --set frontend.tag=${{ github.sha }} --set backend.tag=${{ github.sha }} --set application.ingress.path=//test

                