name: CI / CD
on: push
jobs:
  frontend-build:
      name: Build and publish frontend
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Login to GHCR
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: $GITHUB_ACTOR
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push image
            uses: docker/build-push-action@v2
            with:
              context: frontend
              push: ${{ github.ref == 'refs/heads/main' }}
              tags: "ghcr.io/sigmachirality/gofungyourself-frontend:${{ github.sha }},ghcr.io/sigmachirality/gofungyourself-frontend:latest"
  backend-build:
      name: Build and publish backend
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Login to GHCR
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: $GITHUB_ACTOR
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push image
            uses: docker/build-push-action@v2
            with:
              context: backend
              push: ${{ github.ref == 'refs/heads/main' }}
              tags: "ghcr.io/sigmachirality/gofungyourself-backend:${{ github.sha }},ghcr.io/sigmachirality/gofungyourself-backend:latest"
  deploy:
    name: Deploy latest version of code
    if: github.ref == 'refs/heads/master'
    needs: [frontend-build, backend-build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name cis188 --role-arn arn:aws:iam::474844133309:role/simono --alias fung
          kubectl config set-context --current --namespace=simono
      - name: Apply helm charts
        run: |
          helm upgrade --install test deploy \
          --set frontend.tag=${{ github.sha }} --set backend.tag=${{ github.sha }} --set ingress.path=//test

                